[package]
name = "pallette-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.3"
egui = "0.32.3"
egui_extras = "0.32.3"
env_logger = "0.11.8"

image = "0.25.8"
raqote = "0.8.5"
rfd = "0.15.4"
